
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
legoinventor_position_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - joint_1
    - joint_2
    - joint_3
    - joint_4
  #state_publish_rate: 1

